### ISSUE TITLE
Suggested Azure DSVM cannot be created on a free trial account 

### ISSUE THREAD

**Issue by Brekel** [aribornstein/cvworkshop#1]
It seems the suggested Azure DSVM cannot be created on a free trial account (freshly created):

"Operation results in exceeding quota limits of Core. Maximum allowed: 4, Current in use: 0, Additional requested: 6".

(the animated gifs were very cumbersome to figure out the steps to create the DSVM btw)

Please primarily make sure people can follow your workshop using option 1 (run locally) or provide a workaround for using Azure.

**Comment by Brekel** [comment]
Tried with a Microsoft MVP account with it's accompanying monthly free credits, then the suggested DSVM is greyed out and can't be selected.

**Comment by aribornstein** [comment]
This is excellent feedback you should be able to run it on a less reasource intensive image I was unaware of that and will make sure to come up with a workaround and inform the correct people that this the case.

**Comment by aribornstein** [comment]
This is excellent feedback you should be able to run it on a less reasource intensive image I was unaware of that and will make sure to come up with a workaround and inform the correct people that this the case.
